name: EAS Build & Firebase Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Log in to EAS
        run: eas login --token ${{ secrets.EAS_TOKEN }}

      - name: Build app
        run: eas build --platform android --non-interactive --profile preview

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
          token: ${{ secrets.FIREBASE_AUTH_TOKEN }}
          groups: testers
          file: ./builds/*.apk
