name: EAS Build & Firebase Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Authenticate with EAS
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
        env:
          EXPO_TOKEN: ${{ secrets.EAS_TOKEN }}

      - name: Build app
        env:
          EXPO_TOKEN: ${{ secrets.EAS_TOKEN }}
        run: eas build --platform android --non-interactive --profile preview

      - name: Write Firebase credentials
        run: echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}' > ${{ github.workspace }}/firebase-service-account.json
      
      - name: Check if APK exists
        run: |
         ls -lh android/app/build/outputs/apk/release/
         if [ ! -f android/app/build/outputs/apk/release/app-release.apk ]; then
           echo "APK not found!"
           exit 1
         fi

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
          file: android/app/build/outputs/apk/release/app-release.apk
          groups: testers
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/firebase-service-account.json
